# -*- coding: utf-8 -*-
"""Task2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RlfmPIa4tugucnIKGyS9UE6QR5hrrtvj

# LGMVIP - Image to Pencil Sketch

**Steps**
1. Read Image
2. Coonvert the coloured image to Gray image
3. Convert gray image to blur image
"""

import cv2

from  google.colab.patches import cv2_imshow
img=cv2.imread('/content/pic1.jpg')
cv2_imshow(img)

gray_image=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
cv2_imshow(gray_image)

inverted_image=255-gray_image
cv2_imshow(inverted_image)

"""**GaussianBlur(src,dust,ksize,sigmaX)** This method accepts the following parameters _
src - A mat object representing the source (input image for this operation
ksize - A size object representing the size of the kernel
sigmaX - A variable of the type double representing the Gaussian kernel standard deviation in X direction.
  1. List item
  2. List item
"""

blurred=cv2.GaussianBlur(inverted_image,(21,21),0)

inverted_blurred=cv2.bitwise_not(blurred)
pencil=cv2.divide(gray_image,inverted_blurred,scale=250.0)
cv2_imshow(pencil)

cv2_imshow(img)

cv2_imshow(pencil)

